version: "3"
services:
  envoy:
    build: ./envoy
    ports:
      - "3000:3000"
    links:
      - "server"
  server:
    build: .
    ports:
      - "9090:9090"
    command: "poetry run python app.py --port=9090 --worker=50"
