# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined server."""
import grpc

from qoin.proto import face_mesh_pb2 as qoin_dot_proto_dot_face__mesh__pb2


class FaceMeshStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FaceMeshPullStream = channel.unary_stream(
                '/qoin.FaceMesh/FaceMeshPullStream',
                request_serializer=qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPullRequest.SerializeToString,
                response_deserializer=qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPullReply.FromString,
                )
        self.FaceMeshPushStream = channel.stream_unary(
                '/qoin.FaceMesh/FaceMeshPushStream',
                request_serializer=qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPushRequest.SerializeToString,
                response_deserializer=qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPushReply.FromString,
                )


class FaceMeshServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FaceMeshPullStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FaceMeshPushStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceMeshServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FaceMeshPullStream': grpc.unary_stream_rpc_method_handler(
                    servicer.FaceMeshPullStream,
                    request_deserializer=qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPullRequest.FromString,
                    response_serializer=qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPullReply.SerializeToString,
            ),
            'FaceMeshPushStream': grpc.stream_unary_rpc_method_handler(
                    servicer.FaceMeshPushStream,
                    request_deserializer=qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPushRequest.FromString,
                    response_serializer=qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPushReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qoin.FaceMesh', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceMesh(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FaceMeshPullStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/qoin.FaceMesh/FaceMeshPullStream',
            qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPullRequest.SerializeToString,
            qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPullReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FaceMeshPushStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/qoin.FaceMesh/FaceMeshPushStream',
            qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPushRequest.SerializeToString,
            qoin_dot_proto_dot_face__mesh__pb2.FaceMeshPushReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
